Underwater_SealedChamber_Braille_GoUpHere:
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	.braille "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstRelicanthLastWailord:
	.braille "FIRST COMES\n"
	.braille "RELICANTH.\n"
	.braille "LAST COMES\n"
	.braille "WAILORD.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	.braille "FIRST COMES\n"
	.braille "WAILORD.\n"
	.braille "LAST COMES\n"
	.braille "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	.braille "IN THIS\n"
	.braille "CAVE WE\n"
	.braille "HAVE\n"
	.braille "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	.braille "WE OWE ALL\n"
	.braille "TO THE\n"
	.braille "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	.braille "BUT, WE\n"
	.braille "SEALED THE\n"
	.braille "POKEMON\n"
	.braille "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	.braille "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	.braille "THOSE WITH\n"
	.braille "COURAGE,\n"
	.braille "THOSE WITH\n"
	.braille "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	.braille "OPEN A DOOR.\n"
	.braille "AN ETERNAL\n"
	.braille "POKEMON\n"
	.braille "WAITS.$"

DesertRuins_Braille_UseStrength:
	.braille "RIGHT, RIGHT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "STRENGTH.$"

DesertRuins_Braille_UseRockSmash:
	.braille "LEFT, LEFT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "ROCK SMASH.$"

IslandCave_Braille_WaitTwoMinutes:
	.braille "STOP AND WAIT.\n"
	.braille "WAIT FOR TIME\n"
	.braille "TO PASS TWICE.$"

IslandCave_Braille_RunLapAroundWall:
	.braille "STAY CLOSE\n"
	.braille "TO THE WALL.\n"
	.braille "RUN AROUND\n"
	.braille "ONE LAP.$"

AncientTomb_Braille_AimToTheSky:
	.braille "WITH NEW TIME,\n"
	.braille "HOPE AND LOVE,\n"
	.braille "AIM TO THE SKY\n"
	.braille "IN THE MIDDLE.$"

AncientTomb_Braille_ShineInTheMiddle:
	.braille "THOSE WHO\n"
	.braille "INHERIT OUR\n"
	.braille "WILL, SHINE\n"
	.braille "IN THE MIDDLE.$"
