ItemBall_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

ItemBall_EventScript_ItemGuardSpec::
	finditem ITEM_GUARD_SPEC
	end

ItemBall_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

ItemBall_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

ItemBall_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

ItemBall_EventScript_ItemIron::
	finditem ITEM_IRON
	end

ItemBall_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

ItemBall_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

ItemBall_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ItemBall_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

ItemBall_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

ItemBall_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

ItemBall_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

ItemBall_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ItemBall_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

ItemBall_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

ItemBall_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

ItemBall_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

ItemBall_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

ItemBall_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

ItemBall_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

ItemBall_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

ItemBall_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

ItemBall_EventScript_ItemXSpecial::
	finditem ITEM_X_SPECIAL
	end

ItemBall_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

ItemBall_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

ItemBall_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

ItemBall_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

ItemBall_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

ItemBall_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ItemBall_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ItemBall_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

ItemBall_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

ItemBall_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

ItemBall_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

ItemBall_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

ItemBall_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

ItemBall_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

ItemBall_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ItemBall_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

ItemBall_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

ItemBall_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

ItemBall_EventScript_ItemXDefend::
	finditem ITEM_X_DEFEND
	end

ItemBall_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

ItemBall_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

ItemBall_EventScript_ItemXAttack::
	finditem ITEM_X_ATTACK
	end

ItemBall_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

ItemBall_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

ItemBall_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

ItemBall_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

ItemBall_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

ItemBall_EventScript_ItemTM23::
	finditem ITEM_TM23
	end

ItemBall_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

ItemBall_EventScript_ItemTM02::
	finditem ITEM_TM02
	end

ItemBall_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

ItemBall_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

ItemBall_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

ItemBall_EventScript_ItemTM13::
	finditem ITEM_TM13
	end

ItemBall_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

ItemBall_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

ItemBall_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

ItemBall_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

ItemBall_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

ItemBall_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

ItemBall_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

ItemBall_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

ItemBall_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

ItemBall_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

ItemBall_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

ItemBall_EventScript_ItemTM48::
	finditem ITEM_TM48
	end

ItemBall_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

ItemBall_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

ItemBall_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ItemBall_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

ItemBall_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

ItemBall_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

ItemBall_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

ItemBall_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

ItemBall_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

ItemBall_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

ItemBall_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

ItemBall_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

ItemBall_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

ItemBall_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

ItemBall_EventScript_ItemTM29::
	finditem ITEM_TM29
	end

ItemBall_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

ItemBall_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end
